### ISSUE TITLE
RFE: ability to easily download logs from child gears

### ISSUE THREAD

**Issue by randallt** [openshift/rhc#593]
Right now there is not an easy way to download logs from child gears without long scripting lines... See

http://stackoverflow.com/questions/23571308/how-to-download-logs-from-child-gears/23572936#23572936

It would be nice to be able to do this as a single variation on the "rhc scp" command. One option would be to implement the --gears option like it is for the "rhc ssh <app> '<command>'" command. The result would be multiple files (taking care identical filenames are not overriden) with or without parent directories, or a single zip file that contains the relevant files. An easy command to get them all to a single place would really help with log post-processing and analysis.

**Comment by icflorescu** [comment]
I know it's been a while since the issue was raised, but I just bumped into it today and found that you can use the `scp` command directly, if you know the gear ssh URL, i.e.:

    scp file.txt user@gear_ssh:app-root/data

to upload a file **to** the gear, or

    scp user@gear_ssh:app-root/data/file.txt .

to download **from** the gear.

I posted this on stackoverflow too, as I'm sure other people will face the same issue.
