### ISSUE TITLE
When bundled, the rhc gem breaks ActiveModel validations in Rails 4

### ISSUE THREAD

**Issue by ryanbooker** [openshift/rhc#657]
I have manually installed all the dependencies, one by one, to verify. Once rhc itself is installed all validations fail with: "You need to supply at least one validation".

Remove rhc and they work again.

NOTE:

`validates_presence_of` style validations still work, only `validates :something, presence: true` style fails.

**Comment by tiwillia** [comment]
I can verify this issue:
```
ArgumentError: You need to supply at least one validation
	from /home/tiwillia/.rvm/gems/ruby-2.2.1/gems/activemodel-4.2.3/lib/active_model/validations/validates.rb:109:in `validates'
	from /tmp/test_657/app/models/product.rb:3:in `<class:Product>'
	from /tmp/test_657/app/models/product.rb:1:in `<top (required)>'
```

Here is the bit of ActiveModel where the issue occurs:
```
#activemodel-4.2.3/lib/active_model/validations/validates.rb
      def validates(*attributes)
        defaults = attributes.extract_options!.dup
        validations = defaults.slice!(*_validates_default_keys)

        raise ArgumentError, "You need to supply at least one attribute" if attributes.empty?
        raise ArgumentError, "You need to supply at least one validation" if validations.empty?
[...]
```

This issue appears to be caused by how we overwrite `Hash`'s `slice!` method: https://github.com/openshift/rhc/blob/master/lib/rhc/core_ext.rb#L182-L188

@danmcp do we consider bundling rhc into a rails project a valid use case? `rhc` appears to overwrite several built-in methods that could cause unexpected behavior like this.

**Comment by danmcp** [comment]
It's certainly not designed for the use case.
